### ISSUE TITLE
DM'ing suddenly stops

### ISSUE THREAD

**Issue by Iasonsyk** [RandomBoi69/discord-mass-dm-py#1]
I added a timer with `import time` and `time.sleep(10)` so I don't get banned by discord for spam. After the script dm's around 3 users, it stops dm'ing, but the console acts like it's working. Any help?

**Comment by RandomBoi69** [comment]
it's a mass dm bot so ofc there's high chance discord ban your account
especially you using self bot so create alts and use on your own risk

**Comment by RandomBoi69** [comment]
and as you can check the code there's no error in code or something that breaks script so it because discord detects ur spam even somehow even you are using time.sleep(10)!

**Comment by Iasonsyk** [comment]
thank you very much!
